// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Health struct {
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}

type LoginInput struct {
	APIKey string `json:"apiKey"`
}

type LoginResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
	User    *User  `json:"user,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID          string `json:"id"`
	Description string `json:"description"`
}

type Version struct {
	Version   string `json:"version"`
	BuildTime string `json:"buildTime"`
	GitCommit string `json:"gitCommit"`
}
